spring:
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    platform: h2
    username: sa
    password:
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        use_sql_comments: true
        format_sql: true

###
#   H2 Settings
###
  h2:
    console:
      enabled: true
      path: /console
      settings:
        trace: false
        web-allow-others: true
---
security:
    jwt:
        client-id: testjwtclientid
        client-secret: XY7kmzoNzl100
        grant-type: password
        resource-ids: testjwtresourceid
        scope-read: read
        scope-write: write
    oauth2:
        resource:
            filter-order: 3
    signing-key: MaYzkSjmkzPC57L

server:
  port: 9899